function TableRows({ rowsData }) {
  return rowsData.map((data, index) => {
    return (
      <tr key={index} className="TableDataRows">
        <td>
          <input
            type="text"
            value={data[0]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[1]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[2]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[3]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[4]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[5]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[6]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[7]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[8]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[9]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[10]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[11]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[12]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[13]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[14]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[15]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[16]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[17]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[18]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[19]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[20]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[21]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[22]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[23]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[24]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[25]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[26]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[27]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[28]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[29]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[30]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[31]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[32]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[33]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[34]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[35]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[36]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[37]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[38]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[39]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[40]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[41]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[42]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[43]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[44]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[45]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[46]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[47]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[48]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[49]}
            readOnly
            className="form-control"
          />
        </td>

        <td>
          <input
            type="text"
            value={data[50]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[51]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[52]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[53]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[54]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[55]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[56]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[57]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[58]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[59]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[60]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[61]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[62]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[63]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[64]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[65]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[66]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[67]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[68]}
            readOnly
            className="form-control"
          />
        </td>
        <td>
          <input
            type="text"
            value={data[69]}
            readOnly
            className="form-control"
          />
        </td>
      </tr>
    );
  });
}
export default TableRows;
